### model
model_name_or_path: /root/autodl-tmp/LLM-Research/Meta-Llama-3___1-8B-Instruct
trust_remote_code: false

### method
stage: sft
do_train: true
finetuning_type: lora
quantization_bit: 4                   # 4-bit量化
quantization_method: bitsandbytes     # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]
# double_quant: true                  # 启用双重量化以进一步节省显存
lora_rank: 8
lora_target: all

### dataset
dataset: openreview_qlora
template: llama3
# cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/openreview/qlora_run_20250427_1
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: openreview_qlora_v1


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 0.00003
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
