name: llm-review-sys
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - openreview-py
      - requests
      - beautifulsoup4
      - pandas
      - tqdm
      - transformers
      - datasets
      - torch
      - scikit-learn
      - matplotlib
      - seaborn
      - nltk
      - peft
      - bitsandbytes
      - accelerate
      - env
