name: openreview
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - pip:
      - openreview-py
      - requests
      - beautifulsoup4
      - pandas
      - tqdm
      - transformers
      - datasets
      - scikit-learn
      - matplotlib
      - seaborn
      - nltk
      - peft
      - bitsandbytes
      - accelerate
      - "albumentations==1.3.1"
      - nougat-ocr